local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Lucas", "DarkTheme")
local Tab = Window:NewTab("CFrame & Position")
local Section = Tab:NewSection("CFrame & Position")
Section:NewButton("CFrame", "Copy CFrame", function()
   setclipboard(tostring(game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame))
end)
Section:NewButton("Position", "Copy Position", function()
    setclipboard(tostring(game.Players.LocalPlayer.Character.HumanoidRootPart.Position))
end)
